list: $/jeremydunn/recipebuilder/models/ingredient/columns.yaml
modelClass: JeremyDunn\RecipeBuilder\Models\Ingredient
title: Ingredients
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jeremydunn/recipebuilder/ingredients/update/:id'
